
import { Providers } from "./providers"; 
import "./globals.css";
import { Roboto } from "next/font/google";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const roboto = Roboto({
  weight: ["300", "400", "500", "700"],
  subsets: ["latin"],
  variable: "--font-roboto",
});

export default function RootLayout({ children }) {
  return (
    <Providers>
      <html lang="pt-BR" className={roboto.variable}>
        <body className="antialiased">
          {children}
        </body>
      </html>
    </Providers>
  );
}
